name: macOS release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cd Atif/src/cmake && make

      - name: Rename
        run: cd Atif/src/cmake && mv AtifExe AtifExe.macOS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: macOS
          files: |
            ./Atif/src/cmake/AtifExe.macOS
